// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  hero_section: dynamic(() => import("./HeroSection")),
  product_grid: dynamic(() => import("./ProductGrid")),
  team_grid: dynamic(() => import("./TeamGrid")),
  text_and_image: dynamic(() => import("./TextAndImage")),
  video_block: dynamic(() => import("./VideoBlock")),
};
